name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Run on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "ponkamrakesh@gmail.com"
          git config --global user.name "ponkamrakesh"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Hugging Face token stored in GitHub secrets
        run: |
          git remote add hf https://RakeshPonkam07:$HF_TOKEN@huggingface.co/spaces/RakeshPonkam07/Render
          git push -f hf main
